version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - JWT_SECRET=test-key-for-jwt-token
    depends_on:
      - mongodb
    command: pytest --maxfail=1 --disable-warnings -v

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: